"use client";

import { AlertTriangle, CalendarDays, FilePlus2, Megaphone, Newspaper, Users } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { parisDateKey, parisWeekDateKeys } from "@/lib/publication-activity";

type Match = { id: string; opponent_name: string; starts_at: string; venue: string | null; competition: string | null; location: "HOME" | "AWAY" | "NEUTRAL" };
type Event = { id: string; title: string; starts_at: string; ends_at: string | null; venue: string | null };
type Announcement = { id: string; message: string; type: "info" | "important" | "urgent" };
type Metric = { key: string; count: number };
type Activity = { date: string; count: number };
type Dashboard = { metrics: Metric[]; publishedNewsCount: number; upcomingMatchCount: number; upcomingMatches: Match[]; announcements: Announcement[]; week: { from: string; to: string; events: Event[]; matches: Match[] }; publicationActivity: Activity[] };
type CalendarItem = { id: string; title: string; starts: string; meta: string | null; match: boolean };

const number = new Intl.NumberFormat("fr-FR");
const dateTime = new Intl.DateTimeFormat("fr-FR", { timeZone: "Europe/Paris", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
const time = new Intl.DateTimeFormat("fr-FR", { timeZone: "Europe/Paris", hour: "2-digit", minute: "2-digit" });
const day = new Intl.DateTimeFormat("fr-FR", { timeZone: "Europe/Paris", weekday: "short", day: "numeric", month: "short" });

function isDashboard(value: unknown): value is Dashboard {
  if (!value || typeof value !== "object") return false;
  const d = value as Record<string, unknown>;
  return Array.isArray(d.metrics) && typeof d.publishedNewsCount === "number" && typeof d.upcomingMatchCount === "number" && Array.isArray(d.upcomingMatches) && Array.isArray(d.announcements) && Array.isArray(d.publicationActivity) && !!d.week && typeof d.week === "object";
}
function metric(data: Dashboard, key: string) { return data.metrics.find((item) => item.key === key)?.count ?? 0; }

function Kpi({ label, value, hint, icon: Icon, tone }: { label: string; value: number; hint: string; icon: LucideIcon; tone: "green" | "yellow" | "red" }) {
  const color = tone === "yellow" ? "bg-[#f7c600] text-[#002f1d]" : tone === "red" ? "bg-red-500 text-white" : "bg-[#087044] text-white";
  return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-4"><span className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${color}`}><Icon size={22} aria-hidden /></span><div><p className="text-sm font-medium text-slate-700">{label}</p><p className="mt-1 text-2xl font-black">{number.format(value)}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div></div></article>;
}

export function AdminDashboardLive() {
  const [data, setData] = useState<Dashboard | null>(null), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [error, setError] = useState("");
  async function load() { setState("loading"); try { const response = await fetch("/api/admin/dashboard", { credentials: "same-origin" }); const json: unknown = await response.json(); const envelope = json && typeof json === "object" ? json as { data?: unknown; error?: { message?: string } } : {}; if (!response.ok || !isDashboard(envelope.data)) throw new Error(envelope.error?.message ?? "Réponse invalide."); setData(envelope.data); setState("ready"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Chargement impossible."); setState("error"); } }
  useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, []);
  if (state === "loading") return <div className="mt-5 grid animate-pulse gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Chargement du tableau de bord">{[0, 1, 2, 3].map((i) => <div key={i} className="h-28 rounded-xl bg-slate-200" />)}</div>;
  if (state === "error" || !data) return <div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><p className="font-bold">Le tableau de bord n’a pas pu être chargé.</p><p className="mt-1">{error}</p><button type="button" onClick={() => void load()} className="mt-3 min-h-11 rounded-lg bg-red-700 px-4 font-bold text-white">Réessayer</button></div>;
  const weekDays = parisWeekDateKeys(data.week.from), max = Math.max(...data.publicationActivity.map((item) => item.count), 1);
  return <>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Actualités publiées" value={data.publishedNewsCount} hint="Articles actuellement publiés" icon={Newspaper} tone="green" /><Kpi label="Matchs à venir" value={data.upcomingMatchCount} hint="Matchs programmés ou reportés" icon={CalendarDays} tone="yellow" /><Kpi label="Inscriptions" value={metric(data, "registrations")} hint="Dossiers enregistrés" icon={Users} tone="green" /><Kpi label="Alertes actives" value={data.announcements.length} hint="Annonces actuellement visibles" icon={AlertTriangle} tone="red" /></div>
    <div className="mt-4 grid min-w-0 gap-4 2xl:grid-cols-[minmax(0,2fr)_minmax(280px,.7fr)]">
      <section className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><h2 className="text-lg font-black">Calendrier de la semaine</h2><Link href="/admin/calendrier" className="text-sm font-bold text-[#087044] hover:underline">Voir le calendrier</Link></div><div className="mt-4 grid gap-2 md:grid-cols-7">{weekDays.map((dateKey) => { const items: CalendarItem[] = [...data.week.events.filter((e) => parisDateKey(new Date(e.starts_at)) === dateKey).map((e) => ({ id: `e-${e.id}`, title: e.title, starts: e.starts_at, meta: e.venue, match: false })), ...data.week.matches.filter((m) => parisDateKey(new Date(m.starts_at)) === dateKey).map((m) => ({ id: `m-${m.id}`, title: `vs ${m.opponent_name}`, starts: m.starts_at, meta: m.venue ?? m.competition, match: true }))]; return <div key={dateKey} className="min-w-0 rounded-lg border border-slate-200 bg-slate-50 p-2"><p className="text-center text-xs font-black uppercase text-slate-600">{day.format(new Date(`${dateKey}T12:00:00Z`))}</p><div className="mt-2 space-y-2">{items.map((item) => <div key={item.id} className={`rounded-md border-l-4 p-2 text-xs ${item.match ? "border-[#f7c600] bg-yellow-50" : "border-[#087044] bg-emerald-50"}`}><p className="font-black">{time.format(new Date(item.starts))}</p><p className="mt-1 break-words font-bold">{item.title}</p>{item.meta ? <p className="mt-1 break-words text-slate-600">{item.meta}</p> : null}</div>)}{items.length === 0 ? <p className="py-3 text-center text-xs text-slate-400">Aucun rendez-vous</p> : null}</div></div>; })}</div></section>
      <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-1"><Announcements items={data.announcements} /><Matches items={data.upcomingMatches} /></div>
    </div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)]"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black">Activité des publications</h2>{data.publicationActivity.some((item) => item.count) ? <><div className="mt-5 flex h-40 items-end gap-1" aria-hidden="true">{data.publicationActivity.map((item) => <div key={item.date} className="min-w-0 flex-1 rounded-t bg-[#087044]" style={{ height: `${Math.max(4, item.count / max * 100)}%` }} />)}</div><ul className="sr-only" aria-label="Publications des 30 derniers jours">{data.publicationActivity.map((item) => <li key={item.date}>{item.date} : {item.count} publication{item.count > 1 ? "s" : ""}</li>)}</ul></> : <p className="mt-4 rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">Aucune publication sur les 30 derniers jours.</p>}</section><QuickActions /></div>
  </>;
}

function Announcements({ items }: { items: Announcement[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><h2 className="font-black">Annonces urgentes</h2><Link href="/admin/parametres#annonces" className="text-xs font-bold text-[#087044]">Voir toutes</Link></div><div className="mt-3 divide-y divide-slate-100">{items.slice(0, 5).map((item) => <div key={item.id} className="flex gap-2 py-2"><AlertTriangle size={16} aria-hidden className={item.type === "urgent" ? "text-red-500" : "text-amber-500"} /><p className="text-sm">{item.message}</p></div>)}{!items.length ? <p className="py-5 text-center text-sm text-slate-500">Aucune annonce active.</p> : null}</div></section>; }
function Matches({ items }: { items: Match[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><h2 className="font-black">Prochains matchs</h2><Link href="/admin/calendrier" className="text-xs font-bold text-[#087044]">Voir tous</Link></div><div className="mt-3 divide-y divide-slate-100">{items.slice(0, 4).map((m) => <div key={m.id} className="py-2"><div className="flex justify-between gap-2 text-sm"><p className="font-bold">{m.location === "HOME" ? "ES Viry-Châtillon" : m.opponent_name} — {m.location === "HOME" ? m.opponent_name : "ES Viry-Châtillon"}</p><time className="shrink-0 font-black">{dateTime.format(new Date(m.starts_at))}</time></div>{m.competition ? <p className="mt-1 text-xs text-slate-500">{m.competition}</p> : null}</div>)}{!items.length ? <p className="py-5 text-center text-sm text-slate-500">Aucun match programmé.</p> : null}</div></section>; }
function QuickActions() { const actions: Array<[string, string, LucideIcon, boolean]> = [["Nouvelle actualité", "/admin/actualites", Newspaper, false], ["Ajouter un match", "/admin/calendrier", CalendarDays, true], ["Créer une annonce", "/admin/parametres#annonces", Megaphone, false], ["Ajouter un document", "/admin/inscriptions", FilePlus2, true]]; return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black">Actions rapides</h2><div className="mt-4 grid grid-cols-2 gap-3">{actions.map(([label, href, Icon, yellow]) => <Link key={label} href={href} className={`flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl p-3 text-center text-sm font-black focus-visible:outline-2 focus-visible:outline-offset-2 ${yellow ? "bg-[#f7c600] text-[#002f1d]" : "bg-[#005333] text-white"}`}><Icon size={24} aria-hidden />{label}</Link>)}</div></section>; }
