-- Blocs de contenu éditables additionnels du « CMS » :
-- chiffres clés, valeurs, et pages « Le Club » (histoire, organigramme, stade).
-- La table public.site_settings (clé -> JSONB) existe déjà ; on se contente de
-- semer les valeurs initiales, alignées sur le contenu actuel du site.
-- Listes enveloppées dans un objet ({ "items": [...] } / { "timeline": [...] }…)
-- car la route PUT /api/admin/settings/[key] refuse un tableau JSON nu.

insert into public.site_settings (key, value) values
  ('club_stats', '{"items":[{"label":"Licenciés","value":"+600","iconName":"Users"},{"label":"Éducateurs","value":"50","iconName":"Award"},{"label":"Équipes","value":"30","iconName":"Shield"},{"label":"Places","value":"5 700","iconName":"Building2"},{"label":"Depuis","value":"1958","iconName":"CalendarDays"}]}'::jsonb),
  ('values', '{"items":[{"title":"Respect","text":"Le respect de chacun, règle du jeu.","iconName":"Handshake"},{"title":"Travail","text":"Le travail et l''effort sont nos moteurs.","iconName":"Dumbbell"},{"title":"Solidarité","text":"On se tire toujours vers le haut.","iconName":"HeartHandshake"},{"title":"Ambition","text":"Viser l''excellence pour aller plus loin.","iconName":"Target"},{"title":"Passion","text":"Une passion qui nous unit tous.","iconName":"Trophy"}]}'::jsonb),
  ('histoire', '{"eyebrow":"Notre parcours","title":"Depuis 1958","intro":"L''ES Viry-Châtillon Football grandit avec sa ville. L''histoire du club est celle d''une transmission : former, rassembler et faire progresser.","timeline":[{"year":"1958","title":"Naissance du club","text":"Fusion de l''US Viry et du FC Viry : naissance de l''ES Viry-Châtillon.","iconName":"Flag"},{"year":"1980-90","title":"L''essor de la formation","text":"Développement de la formation et structuration des catégories jeunes.","iconName":"GraduationCap"},{"year":"2000","title":"Ancrage régional","text":"Montée en exigences régionales et rayonnement local renforcé.","iconName":"TrendingUp"},{"year":"Aujourd''hui","title":"Tournés vers l''avenir","text":"Un club familial, formateur et tourné vers l''avenir.","iconName":"HeartHandshake"}]}'::jsonb),
  ('organigramme', '{"title":"Structure du club","intro":"Une organisation claire permet au club d''être lisible pour les familles, les éducateurs et les partenaires.","groups":[{"title":"Bureau","text":"Président, vice-présidents, trésorerie, secrétariat général"},{"title":"Direction sportive","text":"Responsable technique, coordinateurs catégories, référents gardiens"},{"title":"Éducateurs","text":"École de foot, jeunes, seniors, féminines, futsal"},{"title":"Administration","text":"Licences, inscriptions, communication, partenariats"}]}'::jsonb),
  ('stade', '{"address":"Stade Henri Longuet, Avenue de l''Armée Leclerc, 91170 Viry-Châtillon","mapsQuery":"Stade Henri Longuet, Viry-Châtillon","infrastructures":["2 terrains","Vestiaires modernes","Club house convivial","Tribunes supporters"],"gallery":[{"src":"/stade/tribune.jpg","alt":"Tribune principale et piste d''athlétisme du Stade Henri Longuet","caption":"La tribune principale et la piste"},{"src":"/stade/tribune2.jpg","alt":"Vue rapprochée de la tribune depuis la piste","caption":"La tribune vue depuis la piste"}]}'::jsonb)
on conflict (key) do nothing;
